// src/handlers/autoGenerateDaily.js
import { getISODate, stripHtml, removeMarkdownCodeBlock, formatDateToChinese, convertEnglishQuotesToChinese } from '../helpers.js';
import { getFromKV, storeInKV } from '../kv.js';
import { callChatAPIStream } from '../chatapi.js';
import { getGitHubFileSha, createOrUpdateGitHubFile, getDailyReportContent } from '../github.js';
import { dataSources } from '../dataFetchers.js';
import { getSystemPromptSummarizationStepOne } from "../prompt/summarizationPromptZero";
import { getSystemPromptSummarizationStepThree } from "../prompt/summarizationPromptStepThree";
import { insertFoot } from '../foot.js';
import { insertAd } from '../ad.js';
import { marked } from '../marked.esm.js';
import { getAppUrl } from '../appUrl.js';

/**
 * 自动生成日报的完整流程：
 * 1. 从 KV 读取当天数据
 * 2. 自动选择所有内容
 * 3. 调用 AI 生成日报
 * 4. 提交到 GitHub
 * 5. 生成 RSS 内容并写入 KV
 */
export async function handleAutoGenerateDaily(request, env) {
    const url = new URL(request.url);
    const dateStr = url.searchParams.get('date') || getISODate();
    
    console.log(`[autoGenerateDaily] Starting automated daily generation for date: ${dateStr}`);
    
    const logs = [];
    const addLog = (msg) => {
        console.log(msg);
        logs.push(`[${new Date().toISOString()}] ${msg}`);
    };

    try {
        // ========== Step 1: 从 KV 读取当天数据 ==========
        addLog('Step 1: Reading data from KV...');
        const allFetchedData = {};
        const fetchPromises = [];
        
        for (const sourceType in dataSources) {
            if (Object.hasOwnProperty.call(dataSources, sourceType)) {
                fetchPromises.push(
                    getFromKV(env.DATA_KV, `${dateStr}-${sourceType}`).then(data => {
                        allFetchedData[sourceType] = data || [];
                        addLog(`  - ${sourceType}: ${data ? data.length : 0} items`);
                    })
                );
            }
        }
        await Promise.allSettled(fetchPromises);

        // 检查是否有数据
        const totalItems = Object.values(allFetchedData).reduce((sum, arr) => sum + arr.length, 0);
        if (totalItems === 0) {
            addLog('ERROR: No data found in KV for today. Please run /writeData first.');
            return new Response(JSON.stringify({
                success: false,
                error: 'No data found in KV',
                message: '请先调用 /writeData 抓取数据',
                date: dateStr,
                logs: logs
            }), { status: 404, headers: { 'Content-Type': 'application/json; charset=utf-8' } });
        }
        addLog(`Total items found: ${totalItems}`);

        // ========== Step 2: 收集所有内容 ==========
        addLog('Step 2: Collecting all content items...');
        const selectedContentItems = [];
        
        for (const sourceType in allFetchedData) {
            const items = allFetchedData[sourceType];
            for (const item of items) {
                let itemText = "";
                switch (item.type) {
                    case 'news':
                        itemText = `News Title: ${item.title}\nPublished: ${item.published_date}\nUrl: ${item.url}\nContent Summary: ${stripHtml(item.details?.content_html || '')}`;
                        break;
                    case 'project':
                        itemText = `Project Name: ${item.title}\nPublished: ${item.published_date}\nUrl: ${item.url}\nDescription: ${item.description || ''}\nStars: ${item.details?.totalStars || 0}`;
                        break;
                    case 'paper':
                        itemText = `Papers Title: ${item.title}\nPublished: ${item.published_date}\nUrl: ${item.url}\nAbstract/Content Summary: ${stripHtml(item.details?.content_html || '')}`;
                        break;
                    case 'socialMedia':
                        itemText = `socialMedia Post by ${item.authors || 'Unknown'}\nPublished: ${item.published_date}\nUrl: ${item.url}\nContent: ${stripHtml(item.details?.content_html || '')}`;
                        break;
                    default:
                        itemText = `Type: ${item.type}\nTitle: ${item.title || 'N/A'}\nDescription: ${item.description || 'N/A'}\nURL: ${item.url || 'N/A'}`;
                        if (item.published_date) itemText += `\nPublished: ${item.published_date}`;
                        if (item.details?.content_html) itemText += `\nContent: ${stripHtml(item.details.content_html)}`;
                        break;
                }
                if (itemText) {
                    selectedContentItems.push(itemText);
                }
            }
        }
        addLog(`Collected ${selectedContentItems.length} content items`);

        if (selectedContentItems.length === 0) {
            return new Response(JSON.stringify({
                success: false,
                error: 'No valid content items',
                date: dateStr,
                logs: logs
            }), { status: 404, headers: { 'Content-Type': 'application/json; charset=utf-8' } });
        }

        // ========== Step 3: 调用 AI 生成日报 ==========
        addLog('Step 3: Calling AI to generate daily report...');
        
        // Call 1: Summarization
        const fullPromptUser = '\n\n------\n\n' + selectedContentItems.join('\n\n------\n\n') + '\n\n------\n\n';
        const fullPromptSystem = getSystemPromptSummarizationStepOne();
        
        addLog(`  - User prompt length: ${fullPromptUser.length}`);
        
        let outputOfCall2 = null;
        try {
            let processedChunks = [];
            for await (const chunk of callChatAPIStream(env, fullPromptUser, fullPromptSystem)) {
                processedChunks.push(chunk);
            }
            outputOfCall2 = processedChunks.join('');
            if (!outputOfCall2 || outputOfCall2.trim() === "") {
                throw new Error("AI summarization returned empty content.");
            }
            outputOfCall2 = removeMarkdownCodeBlock(outputOfCall2);
            addLog(`  - Summarization complete. Output length: ${outputOfCall2.length}`);
        } catch (error) {
            addLog(`  - ERROR in AI summarization: ${error.message}`);
            throw error;
        }

        // Call 2: Generate summary
        const fullPromptSystem3 = getSystemPromptSummarizationStepThree();
        let outputOfCall3 = null;
        try {
            let processedChunks = [];
            for await (const chunk of callChatAPIStream(env, outputOfCall2, fullPromptSystem3)) {
                processedChunks.push(chunk);
            }
            outputOfCall3 = processedChunks.join('');
            if (!outputOfCall3 || outputOfCall3.trim() === "") {
                throw new Error("AI summary generation returned empty content.");
            }
            outputOfCall3 = removeMarkdownCodeBlock(outputOfCall3);
            addLog(`  - Summary generation complete. Output length: ${outputOfCall3.length}`);
        } catch (error) {
            addLog(`  - ERROR in summary generation: ${error.message}`);
            throw error;
        }

        // 构建最终日报内容
        let dailySummaryMarkdownContent = `## ${env.DAILY_TITLE} ${formatDateToChinese(dateStr)}\n\n`;
        dailySummaryMarkdownContent += '> ' + env.DAILY_TITLE_MIN + '\n\n';
        dailySummaryMarkdownContent += '\n\n### **今日摘要**\n\n```\n' + outputOfCall3 + '\n```\n\n';
        if (env.INSERT_AD === 'true') dailySummaryMarkdownContent += insertAd() + '\n';
        dailySummaryMarkdownContent += `\n\n${outputOfCall2}`;
        if (env.INSERT_FOOT === 'true') dailySummaryMarkdownContent += insertFoot() + '\n\n';

        // ========== Step 4: 提交到 GitHub ==========
        addLog('Step 4: Committing to GitHub...');
        const dailyPath = `daily/${dateStr}.md`;
        try {
            const existingSha = await getGitHubFileSha(env, dailyPath);
            const commitMessage = `${existingSha ? 'Update' : 'Create'} daily report for ${dateStr} (auto-generated)`;
            await createOrUpdateGitHubFile(env, dailyPath, dailySummaryMarkdownContent, commitMessage, existingSha);
            addLog(`  - Successfully committed to ${dailyPath}`);
        } catch (error) {
            addLog(`  - ERROR committing to GitHub: ${error.message}`);
            throw error;
        }

        // ========== Step 5: 生成 RSS 内容并写入 KV ==========
        addLog('Step 5: Generating RSS content and writing to KV...');
        
        // 生成精简版 RSS 内容
        const rssContent = await generateRssAIContent(env, dailySummaryMarkdownContent);
        const rssPath = `rss/${dateStr}.md`;
        
        try {
            const existingRssSha = await getGitHubFileSha(env, rssPath);
            const rssCommitMessage = `${existingRssSha ? 'Update' : 'Create'} RSS content for ${dateStr}`;
            await createOrUpdateGitHubFile(env, rssPath, rssContent, rssCommitMessage, existingRssSha);
            addLog(`  - Successfully committed RSS to ${rssPath}`);
        } catch (error) {
            addLog(`  - WARNING: Failed to commit RSS to GitHub: ${error.message}`);
            // 不抛出错误，继续执行
        }

        // 写入 KV
        const yearMonth = dateStr.substring(0, 7);
        const report = {
            report_date: dateStr,
            title: dateStr + '日刊',
            link: '/' + yearMonth + '/' + dateStr + '/',
            content_html: marked.parse(dailySummaryMarkdownContent),
            published_date: new Date().toISOString()
        };
        
        const kvKey = `${dateStr}-report`;
        await storeInKV(env.DATA_KV, kvKey, report);
        addLog(`  - Successfully stored report in KV with key: ${kvKey}`);

        addLog('All steps completed successfully!');

        return new Response(JSON.stringify({
            success: true,
            message: 'Daily report generated and published successfully',
            date: dateStr,
            totalItems: totalItems,
            dailyPath: dailyPath,
            rssPath: rssPath,
            logs: logs
        }), { headers: { 'Content-Type': 'application/json; charset=utf-8' } });

    } catch (error) {
        addLog(`FATAL ERROR: ${error.message}`);
        console.error('[autoGenerateDaily] Error:', error);
        return new Response(JSON.stringify({
            success: false,
            error: error.message,
            date: dateStr,
            logs: logs
        }), { status: 500, headers: { 'Content-Type': 'application/json; charset=utf-8' } });
    }
}

/**
 * 生成精简版 RSS 内容
 */
async function generateRssAIContent(env, content) {
    const { getSummarizationSimplifyPrompt } = await import('../prompt/summarizationSimplifyPrompt.js');
    const { callChatAPI } = await import('../chatapi.js');
    const { removeMarkdownCodeBlock: removeCodeBlock, truncateContent } = await import('../helpers.js');
    
    try {
        let result = await callChatAPI(env, content, getSummarizationSimplifyPrompt());
        result = removeCodeBlock(result);
        result = truncateContent(result, 360);
        result += "\n\n</br>" + getAppUrl();
        return result;
    } catch (error) {
        console.error('[generateRssAIContent] Error:', error);
        // 如果 AI 生成失败，返回截断的原文
        return content.substring(0, 500) + '\n\n...</br>' + getAppUrl();
    }
}
